[target.aarch64-unknown-linux-gnu]
pre-build = [
	"export DEBIAN_FRONTEND=noninteractive",
	"dpkg --add-architecture $CROSS_DEB_ARCH",
	"apt-get update && apt-get install -y libxcb-render0-dev:$CROSS_DEB_ARCH libxcb-shape0-dev:$CROSS_DEB_ARCH libxcb-xfixes0-dev:$CROSS_DEB_ARCH libspeechd-dev:$CROSS_DEB_ARCH libxkbcommon-dev:$CROSS_DEB_ARCH libssl-dev:$CROSS_DEB_ARCH",
]
